export const SET_CARD_TYPE_FILTER = 'SET_CARD_TYPE_FILTER';
export const SET_COST_AMOUNT_FILTER = 'SET_COST_AMOUNT_FILTER';
export const SET_COST_IN_MONTH_FILTER = 'SET_COST_IN_MONTH_FILTER';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const REQUEST_CARDS = 'REQUEST_CARDS';
export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const SET_DEVICE_TYPE = 'SET_DEVICE_TYPE';
